services:
  mongodb:
    image: mongo:7
    container_name: mall-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: "123456"
    volumes:
      - /opt/mall-dependencies/mongodb/data:/data/db
      - /opt/mall-dependencies/mongodb/configdb:/data/configdb
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --username root --password 123456 --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: mall-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: "123456"
      RABBITMQ_DEFAULT_VHOST: /mall
    volumes:
      - /opt/mall-dependencies/rabbitmq:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10
